apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atcha-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: atcha-app
